package de.verschwiegener.gdtf4j.util;

public enum PhysicalUnit {

	NONE, PERCENT, LENGTH, MASS, TIME, TEMPERATURE, LUMINOUSINTENSITY, ANGLE, FORCE, FREQUENCY, CURRENT, VOLTAGE, POWER,
	ENERGY, AREA, VOLUME, SPEED, ACCELERATION, ANGULARSPEED, ANGULARACCC, WAVELENGTH, COLORCOMPONENT;

}
